### ISSUE TITLE
switch to sqlx for backend database handling

### ISSUE THREAD

**Issue by jodh-intel** [confidential-containers/simple-kbs#16]
The current code requires mysql/mariadb, but if we switched to [`sqlx`](https://github.com/launchbadge/sqlx) we'd provide a more flexible solution that supports a lot more DB servers.

/cc @fitzthum.

**Comment by fitzthum** [comment]
@dunnderr something to think about once the db PR is merged.

**Comment by dubek** [comment]
Interesting suggestion @jodh-intel . Do you know if it will allow us to generate a binary that can work both with mysql and postgres? From their README, I see this comment:

```rust
    // Make a simple query to return the given parameter (use a question mark `?` instead of `$1` for MySQL)
    let row: (i64,) = sqlx::query_as("SELECT $1")
        .bind(150_i64)
        .fetch_one(&pool).await?;
```

If my code has to have `?` or `$1` in the queries then it cannot be used as-is to connect to different databases, I think.

**Comment by dunnderr** [comment]
I think that this sounds like a good idea.  I will dig into the details of sqlx to see how we can migrate to sqlx from mysql.

**Comment by dunnderr** [comment]
I just posted a pull request incorporating sqlx that leverages any to support mysql, postgres, and sqlite.

**Comment by fitzthum** [comment]
#30 merged.
