### ISSUE TITLE
Better error handling for missing keysets

### ISSUE THREAD

**Issue by fitzthum** [confidential-containers/simple-kbs#33]
Currently the KBS fails silently if we request a keyset that is not in the database. We need to add some sort of logging for this.

**Comment by dunnderr** [comment]
Hi Tobin, I will start working on this.

**Comment by ariel-adam** [comment]
@fitzthum is this issue still relevant or can be closed? 
If it's still relevant to what release do you think we should map it to (mid-November, end-December, mid-February etc...)?
