### ISSUE TITLE
Allow secrets and keysets to have a NULL policy

### ISSUE THREAD

**Issue by dubek** [confidential-containers/simple-kbs#35]
After merging #30, `get_secret_policy` and `get_keyset_policy` fail if the polid column has NULL in it.

These function should return something like `Result<Option<Policy>>` (and return `Ok(None)` if the polid is NULL).

**Comment by dunnderr** [comment]
I will make these changes after your PR is merged.

**Comment by dunnderr** [comment]
I have made these changes and would like to review them with you and Tobin before creating another PR.
