### ISSUE TITLE
Add pluggable database backend

### ISSUE THREAD

**Issue by fitzthum** [confidential-containers/simple-kbs#4]
We should support multiple database backends. Rather than connecting to a MySQL server, a user might want to use a SQLite db in a container.

**Comment by larrydewey** [comment]
I agree, this would be a really nice feature. I know there are two general approaches for tackling this, one would be an all encompassing library like [sqlx](https://docs.rs/sqlx/latest/sqlx/), the other adding feature flags. I don't have a preference either way, so let the discussion commence! :)
