### ISSUE TITLE
Support for kbs uri resource indexing

### ISSUE THREAD

**Issue by Xynnn007** [confidential-containers/simple-kbs#57]
Support kbs uri for both keys and resources.
Now the request format is under reviewing here https://github.com/confidential-containers/attestation-agent/pull/129/files#diff-24688ed3518cc206dbc961a052e75291930a4176eecad2e46da73d7834655512R53

The id field follows `<repository>/<type>/<tag>` format, which should be handled in simple-KBS side.

**Comment by fitzthum** [comment]
This should be somewhat straightforward. I have yet to decide if we want to extend the protocol to pass the fields individually (would also require changes to the kata shim) or just parse them from the id. I am thinking that we probably won't support having different repos with simple-kbs.

**Comment by Xynnn007** [comment]
> I am thinking that we probably won't support having different repos with simple-kbs.
Yes, that depends on how simple-kbs works. We can change the AA side code to ignore useless fields and only convert  `<type>/<tag>`

> This should be somewhat straightforward. I have yet to decide if we want to extend the protocol to pass the fields individually (would also require changes to the kata shim) or just parse them from the id.

Sorry I cannot get your point. What does "pass the fields individually" mean? What fields?

**Comment by Xynnn007** [comment]
Can this issue be closed?

**Comment by fitzthum** [comment]
Yup. Turns out we can handle this by just adding more resources to the db.
